on:
  pull_request:
    types: [closed]
    branches:
      - master
name: 🚀FTP Deploy website

jobs:
      web-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        steps:
          - name: 🚚 Get latest code
            uses: actions/checkout@v2

          - name: Use Node.js 16
            uses: actions/setup-node@v2
            with:
              node-version: '16'

          - name: 🔨 Build Project
            run: |
              npm install
              npm run build

          - name: List output files
            run: find build/ -print

          - name: 📂 Sync files
            uses: airvzxf/ftp-deployment-action@latest
            with:
                server: ${{ secrets.FTP_SERVER }}
                user: ${{ secrets.FTP_USERNAME }}
                password: ${{ secrets.FTP_PASSWORD }}
                local_dir: ./www/roulette
                delete: "false"